AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Use lambda to run Athena query and get result

Globals:
  Function:
    Timeout: 900
    Runtime: go1.x
    MemorySize: 128

Parameters:
  S3BucketCostAndUsageRawData:
    Type: String
    Default: "cost-and-usage"
    Description: "s3 bucket name, where the Cost-And-Usage Raw Data are saved."
  # report
  SNSTopicArn:
    Type: String
    Default: "..."
    Description: ""
  AthenaDatabase:
    Type: String
    Default: ""
    Description: ""
  AthenaWorkgroup:
    Type: String
    Default: "primary"
    Description: ""
  

Resources:
  LambdaGenerateAthenaReport:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app
      FunctionName: "generateAthenaReport"
      Description: "cost-and-usage bucket -> event -> lambda, process data -> sns"

      Environment: 
        Variables:
          S3BucketCostAndUsageRawData: !Ref S3BucketCostAndUsageRawData
          SNSTopicArn: !Ref SNSTopicArn
          AthenaDatabase: !Ref AthenaDatabase
          AthenaWorkgroup: !Ref AthenaWorkgroup